new: add ability to retrieve field name via BSONFieldName
aporeto-inc/manipulate pull request #127
Opened 2020-09-18 16:45 UTC by aaslamin

This PR consumes the functionality to add custom BSON field name added to the spec here: https://github.com/aporeto-inc/elemental/pull/76/commits

2020-09-18 17:50 UTC, primalmotion requested changes
Needs tests on options and actual compiler test

2020-09-22 02:17 UTC, aaslamin commented on manipmongo/compiler.go
> +				subs = append(subs, CompileFilter(sub, opts...))
The new unit tests I added cover the recursive cases to ensure the configured options are passed down on recursive calls 🔁 

@primalmotion 👀

2020-09-22 02:18 UTC, aaslamin commented
### Update

• 💯% test coverage has been added for the new `CompilerOption` along with end-to-end tests demonstrating it in action.

2020-09-22 16:56 UTC, aaslamin commented
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "victoria-metrics",
    "component": "manipulate",
    "pr-id": "127",
    "commit-sha": "bf22db4122e4dcf62c73a2c107c8fe3d3c3cad72",
    "pipeline": "master"
  },
  {
    "project": "victoria-metrics",
    "component": "backend",
    "pr-id": "726",
    "commit-sha": "fe450be2aee3ffa59e1fe9d6a2d1ed4958c46e5e",
    "pipeline": "master"
  },
  {
    "project": "victoria-metrics",
    "component": "gaia",
    "pr-id": "471",
    "commit-sha": "8c87f216ac3978968e3d2ff087a3e4c60b60ae1f",
    "pipeline": "master"
  },
  {
    "project": "victoria-metrics",
    "component": "underwater",
    "pr-id": "104",
    "commit-sha": "52843e51e546536d79d893dffb53428d30cf8c5d",
    "pipeline": "master"
  }
]
```

2020-09-22 17:13 UTC, primalmotion approved these changes

2020-09-22 17:18 UTC, merged